# Generated by Django 4.2.8 on 2023-12-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brand_site.post')),
                ('img_url', models.URLField(null=True)),
            ],
            bases=('brand_site.post',),
        ),
        migrations.CreateModel(
            name='PodcastPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brand_site.post')),
                ('pod_url', models.URLField(null=True)),
            ],
            bases=('brand_site.post',),
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brand_site.post')),
                ('vdo_url', models.URLField(null=True)),
                ('video_stamp', models.TextField(max_length=50)),
            ],
            bases=('brand_site.post',),
        ),
    ]
