# Generated by Django 4.2.8 on 2024-01-01 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brand_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastpost',
            name='podcaster',
            field=models.CharField(default='', max_length=100, verbose_name='podcaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcastpost',
            name='record_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='img_url',
            field=models.URLField(null=True, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='podcastpost',
            name='pod_url',
            field=models.URLField(null=True, verbose_name='podcast url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='vdo_url',
            field=models.URLField(null=True, verbose_name='video url'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video_stamp',
            field=models.TextField(max_length=200, verbose_name='video stamp'),
        ),
    ]
