# Generated by Django 4.2.8 on 2024-01-01 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    # point to migration hist
    dependencies = [
        ('brand_site', '0003_alter_podcastpost_record_stamp'),
    ]

    # manuelly make migration, rename field name
    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='update_at')
    ]
